name: Build

on:
  push:

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - x86_64
        sdk:
          - openwrt-21.02

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-netspeedtest
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
 
      - name: Building packages 2
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-netspeedtest
          NO_REFRESH_CHECK: true

      - name: Upload artifacts 2
        uses: actions/upload-artifact@main
        with:
          name: luci-app-netspeedtest-${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
